# Generated by Django 2.0.1 on 2018-01-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('quotation', models.DecimalField(decimal_places=6, max_digits=16)),
                ('quotation_date', models.DateTimeField(verbose_name='date quotation')),
            ],
        ),
    ]
