# Generated by Django 2.0.1 on 2018-01-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_auto_20180113_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='updated_at',
            new_name='last_update',
        ),
    ]
